### ISSUE TITLE
Lin\Huobi\Api\Futures的getDetailMerged方法没有设置path

### ISSUE THREAD

**Issue by 0377** [zhouaini528/huobi-php#2]
$this->type = 'GET';
$this->path = '/market/detail/merged';
$this->data = $data;
return $this->exec();

**Comment by zhouaini528** [comment]
好的谢谢，稍后就做出修改。   如果你愿意可以fork提交你想更改的地方，我这边查阅后和可以合并。这个SDK希望有所有人的贡献
