### ISSUE TITLE
在使用过程中发现两处bug

### ISSUE THREAD

**Issue by wanecho** [zhouaini528/huobi-php#3]
## 感谢您的分享，我在使用过程中遇到的问题并且修复了两处问题
# 第一处
### 文件：在src\Api\WebSocket\SocketServer.php 118行
`switch ($this->config['platform'])`
正确的应该是
`switch ($this->config['platform']['type'])`

# 第二处
### 文件：src\Api\WebSocket\SocketFunction.php 104行
`if(isset($host_tmp[1])) $temp="GET\n" . $host_tmp[2] . ":443\n" . '/ws/v2' . "\n" . implode('&', $param_tmp);`
上面的 “:443”删除 即：
`if(isset($host_tmp[1])) $temp="GET\n" . $host_tmp[2] . "\n" . '/ws/v2' . "\n" . implode('&', $param_tmp);`
子账户签名验证即可通过

**Comment by zhouaini528** [comment]
非常感谢你的发现。   第二处的问题，请问你的现货还是期货？

**Comment by wanecho** [comment]
我是用的现货部分

**Comment by zhouaini528** [comment]
不好意思现在才回复你。你说的问题已经全部解决了，注意更新你的composer。其实你发现代码问题你可以fock  然后提交申请合并，我这边通过就可以合并代码。     这个SDK也有你们的贡献
