### ISSUE TITLE
请问支持U本位交割合约吗？

### ISSUE THREAD

**Issue by bufeetu** [zhouaini528/huobi-php#7]

**Comment by zhouaini528** [comment]
支持的 [https://github.com/zhouaini528/huobi-php/blob/master/tests/linear/trade.php](https://github.com/zhouaini528/huobi-php/blob/master/tests/linear/trade.php)

**Comment by zhouaini528** [comment]
U本位  huobi目前只有  永续的，  交割没有。  看这里https://github.com/zhouaini528/huobi-php/tree/master/tests/swap
